plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'com.formdev', name: 'flatlaf', version: '3.6.2'
    implementation group: 'org.freedesktop.gstreamer', name: 'gst1-java-core', version: '1.4.0'
    testImplementation libs.junit
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'com.tdberg.timer.Main'
}
